version: '3'

services:
  mysql-master:
    image: 'bitnami/mysql:latest'
    hostname: nodo1
    ports:
      - '3306'
    volumes:
      - /mnt/mysql/data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
      - BITNAMI_DEBUG=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.hostname == nodo2]
    networks:  
      - backend          


  mysql-slave:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    volumes:
      - /mnt/mysql/data:/bitnami/mysql/data
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=nodo2
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
      - BITNAMI_DEBUG=true
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.hostname != nodo2]
    networks:
      - backend
    
    maxscale:
      image: mariadb/maxscale:2.4
      depends_on:
          - mysql-master
          - mysql-slave          
      volumes:
          - ./maxscale.cnf.d:/etc/maxscale.cnf.d
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints: [node.role != worker]
      ports:
          - "4006:4006"  # readwrite port
          - "4008:4008"  # readonly port
          - "8989:8989"  # REST API port
      networks:
        - backend
        - frontend

networks:
  backend:
    external: true
  frontend:
    external: true
  
      
